name: Github Pages

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm i -g notablog
          notablog generate .
          ls -R public  # 验证输出

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: SnoopyBug/SnoopyBug.github.io
          branch: gh-pages   # 小写，匹配日志行为
          folder: public     # 小写
          exclude: ".git, .github, .ssh"  # 显式设置，无注释！

# # This is a basic workflow to help you get started with Actions

# name: Github Pages

# # Controls when the workflow will run
# on:
#   schedule:
#     - cron: '0 23 * * *'
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # 拉取代码
#       - name: Checkout
#         uses: actions/checkout@v2
#       # 1、生成静态文件
#       - name: Build
#         run: npm i -g notablog && notablog generate . && ls -ilsh ./
        
#       # 2、部署到 GitHub Pages      
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4.2.5
#         with:
#           token: ${{ secrets.ACCESS_TOKEN }}
#           repository-name: SnoopyBug/SnoopyBug.github.io
#           BRANCH: master
#           FOLDER: public
#           # 注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
